move /Y App.tsx frontend\
move /Y index.tsx frontend\
move /Y index.html frontend\
move /Y vite.config.ts frontend\
move /Y tsconfig.json frontend\
move /Y package.json frontend\
move /Y .env.local frontend\
move /Y components frontend\
move /Y input frontend\
